# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZRV4B3zLxsw9WxsvDmA7y4ia90Pm-FVB
"""

# task3_integration.py
"""
Task 3: System Integration & Interface for Grocery Recommender

This module runs as a script or can be imported in Colab/notebook.

Sections:
  - Task 1: Frequent Itemset Mining (get_frequent_patterns)
  - Task 2: Collaborative Filtering (CollaborativeFilteringRecommender)
  - Task 3: Hybrid Recommender & Evaluation
  - Colab Notebook Example
"""
import pandas as pd
import numpy as np
from collections import defaultdict
from itertools import combinations
from sklearn.metrics.pairwise import cosine_similarity
import os, sys

# Colab dependencies check
try:
    import mlxtend
except ImportError:
    print("Install mlxtend in Colab: !pip install mlxtend")

from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import fpgrowth

def get_frequent_patterns(df, min_support=0.02, recency_weight=False, decay_factor=0.9, user_id = None): #user_id
    """
    FP-Growth per user: drops missing dates to avoid NaT errors.
    """
    user_df = df# df[df['User_id'] == user_id].copy()
    # parse dates, drop rows where parsing fails
    user_df['Date'] = pd.to_datetime(user_df['Date'], dayfirst=True, errors='coerce')
    user_df = user_df.dropna(subset=['Date'])
    if user_df.empty:
        return pd.DataFrame(columns=['itemsets', 'support'])

    txns = user_df.groupby('Date')['itemDescription'].apply(list).reset_index()
    if recency_weight:
        latest = txns['Date'].max()
        txns['weight'] = txns['Date'].apply(lambda d: decay_factor ** ((latest - d).days))
        expanded = []
        for _, row in txns.iterrows():
            repeats = max(1, int(row['weight'] * 10))
            expanded.extend([row['itemDescription']] * repeats)
        transactions = expanded
    else:
        transactions = txns['itemDescription'].tolist()

    te = TransactionEncoder()
    te_ary = te.fit(transactions).transform(transactions)
    trans_df = pd.DataFrame(te_ary, columns=te.columns_)
    patterns = fpgrowth(trans_df, min_support=min_support, use_colnames=True)
    patterns.sort_values('support', ascending=False, inplace=True)
    return patterns

class CollaborativeFilteringRecommender:
    def __init__(self, recency_weighting=True, decay_factor=0.95):
        self.recency_weighting = recency_weighting
        self.decay_factor = decay_factor
        self.user_map = {}
        self.reverse_user_map = {}
        self.item_map = {}
        self.reverse_item_map = {}
        self.user_item_matrix = None
        self.user_similarity = None
        self.fitted = False

    def fit(self, df):
        # copy and parse dates
        df2 = df.copy()
        df2['Date'] = pd.to_datetime(df2['Date'], dayfirst=True, errors='coerce')
        df2 = df2.dropna(subset=['Date'])

        user_items = defaultdict(lambda: defaultdict(float))
        latest = df2['Date'].max()
        for _, row in df2.iterrows():
            u, item, d = row['User_id'], row['itemDescription'], row['Date']
            w = (self.decay_factor ** ((latest - d).days)) if self.recency_weighting else 1.0
            user_items[u][item] += w

        self.user_map = {u: idx for idx, u in enumerate(user_items)}
        self.reverse_user_map = {v: k for k, v in self.user_map.items()}
        items = sorted({it for items in user_items.values() for it in items})
        self.item_map = {it: idx for idx, it in enumerate(items)}
        self.reverse_item_map = {v: k for k, v in self.item_map.items()}

        M = np.zeros((len(self.user_map), len(self.item_map)))
        for u, its in user_items.items():
            ui = self.user_map[u]
            for it, score in its.items():
                M[ui, self.item_map[it]] = score
        self.user_item_matrix = M
        self.user_similarity = cosine_similarity(M)
        self.fitted = True

    def recommend(self, user_id, top_n=5, exclude_items=None):
        if not self.fitted or user_id not in self.user_map:
            return []
        uid = self.user_map[user_id]
        sims = self.user_similarity[uid]
        scores = sims @ self.user_item_matrix
        seen = set(np.where(self.user_item_matrix[uid] > 0)[0])
        if exclude_items:
            seen |= {self.item_map[i] for i in exclude_items if i in self.item_map}
        scores[list(seen)] = 0
        top_idx = np.argsort(scores)[::-1][:top_n]
        return [self.reverse_item_map[i] for i in top_idx if scores[i] > 0]

class HybridRecommender:
    def __init__(self, cf_model, alpha=0.5):
        self.cf = cf_model
        self.alpha = alpha

    def recommend(self, user_id, patterns_df=None, top_n=5, exclude=None):
        cf_scores = {}
        if self.cf.fitted and user_id in self.cf.user_map:
            sims = self.cf.user_similarity[self.cf.user_map[user_id]]
            raw = sims @ self.cf.user_item_matrix
            cf_scores = {self.cf.reverse_item_map[i]: raw[i] for i in np.argsort(raw)[::-1]}
        pat_scores = {}
        if patterns_df is not None and not patterns_df.empty:
            for _, row in patterns_df.iterrows():
                for itm in row['itemsets']:
                    pat_scores[itm] = max(pat_scores.get(itm, 0), row['support'] * len(row['itemsets']))
        all_items = set(cf_scores) | set(pat_scores)
        hybrid = {it: self.alpha * cf_scores.get(it, 0) + (1-self.alpha) * pat_scores.get(it, 0)
                  for it in all_items}
        if exclude:
            for it in exclude:
                hybrid.pop(it, None)
        top = sorted(hybrid.items(), key=lambda x: x[1], reverse=True)[:top_n]
        return [it for it,_ in top]

def precision_at_k(recs, actuals, k=5):
    return sum(1 for r in recs[:k] if r in actuals) / k

def evaluate_models(cf, hybrid, train_df, test_df, top_n=5):
    users = test_df['User_id'].unique()
    p_cf, p_h = [], []
    for u in users:
        actual = test_df[test_df['User_id']==u]['itemDescription'].tolist()
        hist = train_df[train_df['User_id']==u]['itemDescription'].unique().tolist()
        rec_cf = cf.recommend(u, top_n=top_n, exclude_items=hist)
        pats   = get_frequent_patterns(u, train_df)
        rec_h  = hybrid.recommend(u, patterns_df=pats, top_n=top_n, exclude=hist)
        p_cf.append(precision_at_k(rec_cf, actual, top_n))
        p_h.append(precision_at_k(rec_h, actual, top_n))
    return np.mean(p_cf), np.mean(p_h)

def main(train_path, test_path=None):
    train = pd.read_csv(train_path)
    cf = CollaborativeFilteringRecommender()
    cf.fit(train)
    hybrid = HybridRecommender(cf_model=cf, alpha=0.6)

    # Notebook detection
    if not sys.stdin.isatty():
        print("Notebook context; returning models.")
        return cf, hybrid, train

    print("Welcome to the Grocery Recommender System!")
    while True:
        uid = input("Enter user_id (or 'exit'): ").strip()
        if uid.lower() == 'exit': break
        opt = input("with or without patterns? ").strip().lower()
        hist = train[train['User_id']==uid]['itemDescription'].tolist()
        if opt=='without':
            recs = cf.recommend(uid, exclude_items=hist)
            print("CF-only:", recs)
        else:
            pats = get_frequent_patterns(uid, train)
            recs = hybrid.recommend(uid, patterns_df=pats, exclude=hist)
            print("Hybrid:", recs)
        print()

    if test_path and os.path.exists(test_path):
        test = pd.read_csv(test_path)
        p_cf, p_h = evaluate_models(cf, hybrid, train, test)
        print(f"Precision@5 CF-only: {p_cf:.3f}")
        print(f"Precision@5 Hybrid:   {p_h:.3f}")

if __name__ == '__main__':
    args = sys.argv[1:]
    if not args: print("Usage: python task3_integration.py <train_csv> [<test_csv>]")
    else: main(*args)

# Colab Notebook Example
# ----------------------
# 1) !pip install mlxtend
# 2) from google.colab import drive; drive.mount('/content/drive')
# 3) files.upload()  # upload this script
# 4) import task3_integration as tri
#    cf_model, hybrid_model, train_df = tri.main(
#      '/content/drive/MyDrive/train.csv',
#      '/content/drive/MyDrive/test.csv')
# 5) uid='U1001'; hist=train_df[train_df['User_id']==uid]['itemDescription'].tolist()
#    pats=tri.get_frequent_patterns(uid,train_df)
#    print('CF-only:', cf_model.recommend(uid,exclude_items=hist))
#    print('Hybrid :', hybrid_model.recommend(uid,patterns_df=pats,exclude=hist))