# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZRV4B3zLxsw9WxsvDmA7y4ia90Pm-FVB
"""

# task3_integration.py
"""
Task 3: System Integration & Interface for Grocery Recommender

This module is self-contained (no external Task1/Task2 modules needed).
It integrates:
  - AprioriMiner & FrequentPatternMiner (Task 1)
  - CollaborativeFilteringRecommender (Task 2)
  - HybridRecommender & Evaluation (Task 3)

Usage:
 As script:
   python task3_integration.py train.csv [test.csv]
 In Colab/notebook:
   cf, hybrid, train_df = main(train_path, test_path)
"""
import pandas as pd
import numpy as np
import os, sys
from collections import defaultdict
from itertools import combinations
from sklearn.metrics.pairwise import cosine_similarity

# --- Task 1: AprioriMiner & FrequentPatternMiner -------------------------
class AprioriMiner:
    """Implements Apriori to find frequent itemsets."""
    def __init__(self, min_support=0.005):
        self.min_support = min_support
        self.frequent_itemsets = {}  # {k: [(itemset, support), ...]}
        self.item_support = {}       # support for all 1-itemsets

    def fit(self, transactions):
        self.transactions = transactions
        n = len(transactions)
        min_count = self.min_support * n
        # count individual items
        counts = defaultdict(int)
        for txn in transactions:
            for item in set(txn): counts[item] += 1
        # L1
        L1 = []
        for item, cnt in counts.items():
            if cnt >= min_count:
                sup = cnt / n
                self.item_support[frozenset([item])] = sup
                L1.append((frozenset([item]), sup))
        self.frequent_itemsets[1] = L1
        prev_L = [iset for iset,_ in L1]
        k = 1
        # iterative
        while prev_L:
            k += 1
            # candidates
            Ck = []
            prev_sets = prev_L
            for i in range(len(prev_sets)):
                for j in range(i+1, len(prev_sets)):
                    union = prev_sets[i] | prev_sets[j]
                    if len(union)==k and union not in Ck:
                        Ck.append(union)
            # count support
            Ck_counts = defaultdict(int)
            for txn in transactions:
                tset = set(txn)
                for cand in Ck:
                    if cand.issubset(tset): Ck_counts[cand]+=1
            # filter
            Lk = []
            for cand, cnt in Ck_counts.items():
                if cnt>=min_count:
                    sup = cnt/n
                    Lk.append((cand, sup))
            if Lk:
                self.frequent_itemsets[k] = Lk
                prev_L = [iset for iset,_ in Lk]
            else:
                break
        return self.frequent_itemsets

class FrequentPatternMiner:
    """Wraps AprioriMiner to provide a simple get_patterns() API."""
    def __init__(self, min_support=0.005):
        self.miner = AprioriMiner(min_support=min_support)
        self.transactions = None

    def fit(self, df, user_id=None):
        # prepare transactions by user (or full)
        if user_id:
            df_u = df[df['User_id']==user_id]
        else:
            df_u = df
        df_u = df_u.copy()
        df_u['Date'] = pd.to_datetime(df_u['Date'], dayfirst=True, errors='coerce')
        df_u = df_u.dropna(subset=['Date'])
        # group by (user, date) pairs or by date alone
        txns = df_u.groupby(['User_id','Date'])['itemDescription'].apply(list).tolist()
        if not txns:
            # fallback to full dataset
            txns = df.groupby(['User_id','Date'])['itemDescription'].apply(list).tolist()
        self.transactions = txns
        self.miner.fit(txns)
        return self

    def get_patterns(self, top_n=10):
        # flatten all frequent itemsets
        flat = []
        for k, lst in self.miner.frequent_itemsets.items():
            for (iset, sup) in lst:
                flat.append((tuple(iset), sup))
        # sort by support descending
        flat.sort(key=lambda x: x[1], reverse=True)
        return flat[:top_n]

# --- Task 2: Collaborative Filtering -------------------------------------
class CollaborativeFilteringRecommender:
    """User-based CF with optional recency weighting."""
    def __init__(self, recency_weighting=True, decay=0.95):
        self.recency = recency_weighting
        self.decay = decay
        self.user_map = {}
        self.item_map = {}
        self.user_item_matrix = None
        self.sim = None
        self.fitted=False

    def fit(self, df):
        df2 = df.copy()
        df2['Date'] = pd.to_datetime(df2['Date'], dayfirst=True, errors='coerce')
        df2 = df2.dropna(subset=['Date'])
        latest = df2['Date'].max()
        # build weights
        user_items = defaultdict(lambda: defaultdict(float))
        for _,r in df2.iterrows():
            u,i,d = r['User_id'], r['itemDescription'], r['Date']
            w = self.decay**((latest-d).days) if self.recency else 1.0
            user_items[u][i]+=w
        # maps
        users = list(user_items.keys())
        items = sorted({i for ui in user_items.values() for i in ui})
        self.user_map={u:idx for idx,u in enumerate(users)}
        self.item_map={i:idx for idx,i in enumerate(items)}
        # matrix
        M = np.zeros((len(users),len(items)))
        for u,ui in user_items.items():
            ui_idx=self.user_map[u]
            for i,w in ui.items(): M[ui_idx,self.item_map[i]]=w
        self.user_item_matrix=M
        self.sim=cosine_similarity(M)
        self.fitted=True
        return self

    def recommend(self, user_id, top_n=5, exclude_items=None):
        if not self.fitted or user_id not in self.user_map:
            return []
        uidx=self.user_map[user_id]
        scores=self.sim[uidx]@self.user_item_matrix
        seen=set(np.where(self.user_item_matrix[uidx]>0)[0])
        if exclude_items:
            seen|={self.item_map[i] for i in exclude_items if i in self.item_map}
        scores[list(seen)]=0
        idxs=np.argsort(scores)[::-1][:top_n]
        return [list(self.item_map.keys())[list(self.item_map.values()).index(i)] for i in idxs if scores[i]>0]

# --- Task 3: Hybrid & Evaluation -----------------------------------------
class HybridRecommender:
    """Blends CF and pattern scores with weight alpha."""
    def __init__(self, cf_model, alpha=0.5):
        self.cf=cf_model
        self.alpha=alpha

    def recommend(self, user_id, patterns, top_n=5, exclude=None):
        # CF scores
        cf_scores={}
        if self.cf.fitted and user_id in self.cf.user_map:
            raw=self.cf.sim[self.cf.user_map[user_id]]@self.cf.user_item_matrix
            for idx,val in enumerate(raw): cf_scores[idx]=val
        # pattern scores uses patterns list of (item_tuple, sup)
        pat_scores={itm[0]:itm[1] for itm in patterns}
        # combine
        items=set(cf_scores.keys())|set(self.cf.item_map.get(x,-1) for x in pat_scores)
        hybrid_scores={i:self.alpha*cf_scores.get(i,0)+(1-self.alpha)*pat_scores.get(i,0) for i in items if i!=-1}
        # exclude
        if exclude:
            for it in exclude:
                if it in self.cf.item_map:
                    hybrid_scores.pop(self.cf.item_map[it],None)
        # top
        top_ids=sorted(hybrid_scores, key=hybrid_scores.get, reverse=True)[:top_n]
        inv_item_map={v:k for k,v in self.cf.item_map.items()}
        return [inv_item_map[i] for i in top_ids]

def precision_at_k(recs, actuals, k=5):
    return sum(1 for r in recs[:k] if r in actuals)/k


def evaluate_models(cf, hybrid, train_df, test_df, top_n=5):
    users=test_df['User_id'].unique()
    pc,ph=[],[]
    miner=FrequentPatternMiner()
    for u in users:
        actual=test_df[test_df['User_id']==u]['itemDescription'].tolist()
        hist=train_df[train_df['User_id']==u]['itemDescription'].tolist()
        rec_cf=cf.recommend(u,exclude_items=hist)
        miner.fit(train_df,user_id=u)
        pats=miner.get_patterns(top_n)
        rec_h=hybrid.recommend(u,pats,exclude=hist)
        pc.append(precision_at_k(rec_cf,actual,top_n))
        ph.append(precision_at_k(rec_h,actual,top_n))
    return np.mean(pc),np.mean(ph)


def main(train_path,test_path=None):
    df=pd.read_csv(train_path)
    cf=CollaborativeFilteringRecommender().fit(df)
    hybrid=HybridRecommender(cf,alpha=0.6)
    if not sys.stdin.isatty(): return cf,hybrid,df
    print("CLI Grocery Recommender")
    while True:
        uid=input("user_id (or exit):").strip()
        if uid=='exit': break
        opt=input("with/without patterns:").strip()
        hist=df[df['User_id']==uid]['itemDescription'].tolist()
        if opt=='without': recs=cf.recommend(uid,exclude_items=hist)
        else:
            miner=FrequentPatternMiner().fit(df,user_id=uid)
            pats=miner.get_patterns(5)
            recs=hybrid.recommend(uid,pats,exclude=hist)
        print(recs)
    if test_path and os.path.exists(test_path):
        test=pd.read_csv(test_path)
        pc,ph=evaluate_models(cf,hybrid,df,test)
        print(f"P@5 CF: {pc:.3f}, Hybrid: {ph:.3f}")

if __name__=='__main__':
    args=sys.argv[1:]
    if not args: print("Usage: python task3_integration.py train.csv [test.csv]")
    else: main(*args)

# --- Colab Notebook Example ----------------------------------------------
# Cell 1: !pip install sklearn pandas mlxtend
# Cell 2: from google.colab import drive; drive.mount('/content/drive')
# Cell 3: from google.colab import files; files.upload()
# Cell 4: import task3_integration as tri
#          cf,hybrid,df=tri.main('/content/train.csv','/content/test.csv')
# Cell 5: uid=df['User_id'].iloc[0]; hist=df[df['User_id']==uid]['itemDescription'].tolist()
#          miner=tri.FrequentPatternMiner().fit(df,user_id=uid)
#          pats=miner.get_patterns(5)
#          print(tri.CollaborativeFilteringRecommender().recommend(uid,exclude_items=hist))
#          print(hybrid.recommend(uid,pats,exclude=hist))
# Cell 6: pc,ph=tri.evaluate_models(cf,hybrid,df,pd.read_csv('/content/test.csv')); print(pc,ph)